---
title: "Hyd24-12"
author: "Rasmus Kirkegaard"
date: "Saturday, August 9, 2014"
output: html_document
---

## Load data and R packages

```{r Loaddata, message=FALSE, warning=FALSE, results='hide'}
library("mmgenome")
mmimport("Load_data.Rmd")
```

Print version numbers etc.
```{r}
sessionInfo()
```


```{r}
# Mark the clusters that has already been extracted
oldtable<-read.table("genomesextracted.txt", row.names=1)
oldtable_trans<-as.data.frame(t(oldtable))
oldtable_trans[,"Coverage.R50AS"]<-as.numeric(as.character(oldtable_trans[,"Coverage.R50AS"]))
oldtable_trans[,"Coverage.R50FOAM"]<-as.numeric(as.character(oldtable_trans[,"Coverage.R50FOAM"]))
myGG<-mmplot(data = d, x = "R50AS", y = "R50FOAM", log.x = T, log.y = T, color = "phylum", minlength = 5000)
myGG<-myGG +  geom_point(data=oldtable_trans, mapping=aes(x=Coverage.R50AS, y=Coverage.R50FOAM),colour="black", fill="white", size=9, shape=21) + scale_fill_discrete(guide="none")
for (i in 1:dim(oldtable_trans)[1]) {
  myGG<-myGG+annotate("text",x=oldtable_trans[i,"Coverage.R50AS"],y=oldtable_trans[i,"Coverage.R50FOAM"],label=i,fontface="bold",size=4)  
}
myGG
```

## Initial extraction

```{r, fig.width=12, fig.height=10, fig.align='center'}
mmplot(data = d, x = "R50AS", y = "R50FOAM", log.x = T, log.y = T, color = "none", minlength = 3000, highlight = 249)

p <- mmplot(data = d, x = "R50AS", y = "R50FOAM", log.x = T, log.y = T, color = "phylum", minlength = 3000)

#p
#sel <- mmplot_locator(p)

sel <- data.frame(R50AS  =  c(7, 13, 13, 7),
                  R50FOAM  =  c(40, 40, 25, 25))

mmplot_selection(p, sel)
```

Extract the scaffolds in the selection.
```{r extractA}
dA <- mmextract(d, sel)
```

Look at the basic stats.
```{r statsA}
mmstats(dA, ncov = 5)
```

```{r}
mmplot_pairs(dA,variables = c("R50AS","R50FOAM","gc","PC1","PC2","PC3"))
```

```{r zoomA, fig.width=12, fig.height=10, fig.align='center'}
p <- mmplot(data = dA, x = "PC2", y = "gc", log.x = T, log.y = T, color = "phylum", minlength = 3000)

#p
#sel <- mmplot_locator(p)

sel <- data.frame(PC2  =  c(0.0298, 0.0347, 0.179, 0.164),
                  gc  =  c(66.6, 59.1, 59.5, 66.4))


mmplot_selection(p, sel)
```


Extract the scaffolds in the selection.
```{r extractB}
dB <- mmextract(dA, sel)
```

Look at the basic stats.
```{r statsB}
mmstats(dB, ncov = 5)
```

```{r plot_networkB, fig.align='center', fig.height=10, fig.width=12}
mmplot_network(data = dB, network = pe, color = "R50AS", nconnections = 10)
```

```{r}
mmref(data = dB,tax.level = "Phylum",tax.compare = "all")
```


```{r}
dC <- mmextract_network(subset = dB, original = d, network = pe, nconnections = 10, type =  "direct")
mmstats(dC, ncov = 5)
```

```{r}
mmplot_network(data = dC, network = pe, color = "R50AS", nconnections = 10)
```

```{r}
p <- mmplot(data = dC, x = "R50AS", y = "R50FOAM", log.x = T, log.y = T, color = "phylum", minlength = 3000)

p
```

```{r}
mmplot_pairs(dC,variables = c("R50AS","R50FOAM","gc","PC1","PC2","PC3"))
```

```{r}
p <- mmplot(data = dC, x = "gc", y = "R50FOAM", log.x = T, log.y = T, color = "phylum", minlength = 3000)

#p
#sel <- mmplot_locator(p)

sel <- data.frame(gc  =  c(60.6, 65.9, 66, 60.5),
                  R50FOAM  =  c(40.5, 41, 27.8, 27.4))


mmplot_selection(p, sel)
```

Extract the scaffolds in the selection.
```{r extractD}
dD <- mmextract(dC, sel)
```

Look at the basic stats.
```{r statsD}
mmstats(dD, ncov = 5)
```

```{r}
mmplot_network(data = dD, network = pe, color = "R50AS", nconnections = 10)
```

```{r}
mmplot(data = d, x = "R50AS", y = "R50FOAM", log.x = T, log.y = T, color = "none", minlength = 1000, highlight = dD)
```

```{r}
mmexport(data = dD,assembly = assembly,file = "Hyd24-12_Randers.fa")
```

```{r}
# Store statsdata for marking up the clusters that has been extracted
stats<-mmstats(dD, ncov=5)
name<-as.character(dD$scaffolds$lca_tax_slv[which(dD$scaffolds$lca_tax_slv!="NA")])[1]
finalstats<-rbind(name,stats)
oldtable<-read.table("genomesextracted.txt", row.names=1)

# Test if stats have already been registered
posdups<-which(finalstats[c(8),]==oldtable[c(8),])
posdups2<-which(finalstats[c(9),]==oldtable[c(9),])
if (anyDuplicated(c(posdups,posdups2))<1) {
show(paste(name," has now been saved "))
newtable<-cbind(oldtable,finalstats)
write.table(newtable,"genomesextracted.txt")
} else {
show("Genome already registered with these coverages")
}
#
```