---
title: "Load Data"
author: "Mads Albertsen"
date: "Monday, August 4, 2014"
output: html_document
---

## Load needed packages

In case you havn't installed all the needed packages, they can be installed via e.g. `install_github("MadsAlbertsen/mmgenome/mmgenome")`.
```{r Load_packages, message=F,warning=FALSE}
library("mmgenome")
options(scipen = 8)
```

## Load all data

Load the raw data.
```{r Load_data}
assembly <- readDNAStringSet("data/assembly.fa", format = "fasta")

V40AS <- read.csv("data/LIB-RHK-526-A-1_1 mapping.csv", header = T)[,c("Reference.sequence","Average.coverage")]               
V40FOAM <- read.csv("data/LIB-RHK-527-A-1_1 mapping.csv", header = T)[,c("Reference.sequence","Average.coverage")]                 
V50AS <- read.csv("data/LIB-RHK-528-A-1_1 mapping.csv", header = T)[,c("Reference.sequence","Average.coverage")]
V50FOAM <- read.csv("data/LIB-RHK-529-A-1_1 mapping.csv", header = T)[,c("Reference.sequence","Average.coverage")]                


ess <- read.table("data/essential.txt", header = T)
tax <- read.delim("data/tax.txt", header = T)

pe <- read.delim("data/network.txt", header = T)
#mp <- read.delim("data/network_mp.txt", header = T)

rRNA16S <- read.delim("data/16S.csv", header = T,sep = ";")
scaffold<-rep(0,times =dim(rRNA16S)[1] )
for (i in 1:dim(rRNA16S)[1]) {
  scaffold[i]<-unlist(strsplit(x = as.character(rRNA16S$sequence_identifier[i]),split = "[.]"))[1]
}
rRNA16S<-cbind(scaffold,rRNA16S)
strsplit(x = as.character(rRNA16S$sequence_identifier[1]),split = "[.]")
#pps <- read.table("data/pps.txt", sep = "\t", header = F, col.names = c("scaffold","pps_root", "pps_kingdom", "pps_phylum", "pps_class", "pps_order", "pps_family", "pps_genus", "pps_species"))[,c(1,4,5,6,7,8)]
#pps[pps == ""] <- NA
```

All data is combined into a single dataframe `d`.
```{r Merge_d1}
d <- mmload(assembly = assembly, 
           coverage = c("V40AS", "V40FOAM","V50AS", "V50FOAM"), 
           tax = tax,
           essential = ess,
           tax.expand = "Proteobacteria",
           tax.freq = 50,
           other = c("rRNA16S")#, "pps"
           )
```

Remove temporary data.
```{r remove}
rm(list = c("V40AS","V40FOAM","V50AS", "V50FOAM", "ess", "tax", "rRNA16S"))
```